function createSettingsPanel({settings, controller, getCurrentServer, describeServer}) {
  const root = document.createElement("div");
  root.className = "focusprofiles-settings";
  const render = () => {
    const profiles = settings.get("profiles");
    const active = controller.getActive();
    const activeProfile = profiles.find((profile) => profile.id === active?.profileId);
    root.innerHTML = `<style>${styles()}</style>
      <div class="fp-header"><div><h2>Focus Profiles</h2><p>Choose a profile from Discord's account popout. Each profile can change your status, optionally end on a timer, mute channels, and hide channels locally.</p></div>${activeProfile ? `<button class="fp-button fp-secondary" data-clear>Clear ${escape(activeProfile.name)}</button>` : ""}</div>
      <div class="fp-active">${activeProfile ? `Active now: <strong>${escape(activeProfile.name)}</strong>${active.expiresAt ? ` — ends ${escape(time(active.expiresAt))}` : ""}` : "No profile is active."}</div>
      <div class="fp-list">${profiles.map((profile) => renderProfile(profile, profiles.length, describeServer, active?.profileId)).join("")}</div>
      ${profiles.length < 8 ? `<button class="fp-button fp-secondary fp-add" data-add-profile>+ Add profile</button>` : ""}`;
  };
  root.addEventListener("change", (event) => {
    const timeControl = event.target.closest("[data-time-control]");
    if (timeControl) {
      const [id, field] = timeControl.dataset.timeControl.split(":");
      const text = timeControl.querySelector(".fp-time-input").value;
      const period = timeControl.querySelector(".fp-time-period").value;
      const value = timeFrom12(text, period);
      if (value) settings.updateProfile(id, {[field]: value});
      render();
      return;
    }
    const input = event.target.closest("[data-field]"); if (!input) return;
    const [id, field] = input.dataset.field.split(":");
    settings.updateProfile(id, {[field]: input.value}); render();
  });
  root.addEventListener("click", (event) => {
    if (event.target.closest("[data-clear]")) { controller.clear(); render(); return; }
    if (event.target.closest("[data-add-profile]")) { addProfile(settings); render(); return; }
    const enable = event.target.closest("[data-enable]"); if (enable) { controller.activate(enable.dataset.enable); render(); return; }
    const remove = event.target.closest("[data-remove-profile]"); if (remove) { settings.set("profiles", settings.get("profiles").filter((profile) => profile.id !== remove.dataset.removeProfile)); render(); return; }
    const add = event.target.closest("[data-add-current]"); if (add) { addCurrent(settings, add.dataset.addCurrent, getCurrentServer()); render(); return; }
    const removeChannel = event.target.closest("[data-remove-channel]"); if (removeChannel) { const [profileId, field, channelId] = removeChannel.dataset.removeChannel.split(":"); const profile = settings.get("profiles").find((item) => item.id === profileId); settings.updateProfile(profileId, {[field]: profile[field].filter((id) => id !== channelId)}); render(); }
  });
  render(); return root;
}

function renderProfile(profile, count, describeServer, activeId) {
  const isActive = profile.id === activeId;
  return `<section class="fp-card ${isActive ? "is-active" : ""}"><div class="fp-card-top"><div class="fp-fields"><label>Name<input data-field="${escape(profile.id)}:name" value="${escape(profile.name)}"></label><label>Status<select data-field="${escape(profile.id)}:status">${["online", "idle", "dnd", "invisible"].map((status) => `<option value="${status}" ${profile.status === status ? "selected" : ""}>${label(status)}</option>`).join("")}</select></label><label>Timer (minutes)<input type="number" min="0" max="4320" data-field="${escape(profile.id)}:durationMinutes" value="${profile.durationMinutes}"></label></div><div class="fp-card-actions">${isActive ? "<span class=\"fp-live\">Active</span>" : ""}<button class="fp-button" data-enable="${escape(profile.id)}">${isActive ? "Reapply" : "Enable"}</button>${count > 1 ? `<button class="fp-icon" title="Delete profile" data-remove-profile="${escape(profile.id)}">×</button>` : ""}</div></div>${profile.status === "dnd" ? `<label class="fp-dnd-text">DND message <input maxlength="128" placeholder="Optional message shown with your DND status" data-field="${escape(profile.id)}:dndText" value="${escape(profile.dndText)}"></label>` : ""}<p class="fp-timer-note">Use 0 to keep the profile on until you clear it. A scheduled stop takes priority if it comes first.</p><div class="fp-schedule">${scheduleControl("Turn on", "enable", profile, "Now", "At a time")}${scheduleControl("Turn off", "disable", profile, "Manually", "At a time")}</div><div class="fp-rules">${rule("Mute server notifications", "mutedGuildIds", profile, describeServer)}${rule("Hide server from sidebar", "hiddenGuildIds", profile, describeServer)}</div></section>`;
}
function scheduleControl(title, kind, profile, defaultLabel, scheduleLabel) { const modeField = `${kind}Mode`; const timeField = `${kind}Time`; const clock = timeTo12(profile[timeField]); return `<div class="fp-schedule-control"><span>${title}</span><select data-field="${escape(profile.id)}:${modeField}"><option value="${kind === "enable" ? "now" : "manual"}" ${profile[modeField] === (kind === "enable" ? "now" : "manual") ? "selected" : ""}>${defaultLabel}</option><option value="scheduled" ${profile[modeField] === "scheduled" ? "selected" : ""}>${scheduleLabel}</option></select>${profile[modeField] === "scheduled" ? `<span class="fp-time" data-time-control="${escape(profile.id)}:${timeField}"><input class="fp-time-input" aria-label="Time" inputmode="numeric" maxlength="5" value="${clock.time}"><select class="fp-time-period" aria-label="AM or PM"><option ${clock.period === "AM" ? "selected" : ""}>AM</option><option ${clock.period === "PM" ? "selected" : ""}>PM</option></select></span>` : ""}</div>`; }
function rule(title, field, profile, describeServer) { const ids = profile[field]; const note = field === "mutedGuildIds" ? "Silences notifications for the whole server while active. The plugin restores the old setting when it ends." : "Removes this server icon from your sidebar on this computer only. Notifications are unchanged."; return `<div class="fp-rule"><div class="fp-rule-top"><strong>${title}</strong><button class="fp-link" data-add-current="${escape(profile.id)}:${field}">Add current server</button></div><p class="fp-rule-note">${note}</p><div class="fp-chips">${ids.length ? ids.map((id) => `<span class="fp-chip">${escape(describeServer(id))}<button title="Remove" data-remove-channel="${escape(profile.id)}:${field}:${escape(id)}">×</button></span>`).join("") : "<span class=\"fp-empty\">No servers added</span>"}</div></div>`; }
function addCurrent(settings, encoded, server) { if (!server?.id) { BdApi.UI.showToast("Open a channel in the server you want to add first.", {type: "error"}); return; } const [profileId, field] = encoded.split(":"); const profile = settings.get("profiles").find((item) => item.id === profileId); settings.updateProfile(profileId, {[field]: [...new Set([...profile[field], server.id])]}); }
function addProfile(settings) { const profiles = settings.get("profiles"); const id = `profile-${Date.now()}`; settings.set("profiles", [...profiles, {id, name: "New Profile", status: "online", durationMinutes: 0, dndText: "", enableMode: "now", enableTime: "09:00", disableMode: "manual", disableTime: "17:00", mutedGuildIds: [], hiddenGuildIds: []}]); }
function label(status) { return {online:"Online", idle:"Idle", dnd:"Do Not Disturb", invisible:"Invisible"}[status]; }
function time(value) { return new Date(value).toLocaleTimeString([], {hour:"numeric", minute:"2-digit"}); }
function timeTo12(value) { const [hour, minute] = String(value || "09:00").split(":").map(Number); return {time: `${hour % 12 || 12}:${String(minute || 0).padStart(2, "0")}`, period: hour < 12 ? "AM" : "PM"}; }
function timeFrom12(value, period) { const match = String(value).trim().match(/^(1[0-2]|0?[1-9]):([0-5]\d)$/); if (!match) return null; let hour = Number(match[1]) % 12; if (period === "PM") hour += 12; return `${String(hour).padStart(2, "0")}:${match[2]}`; }
function escape(value) { return String(value).replace(/[&<>"']/g, (char) => ({"&":"&amp;", "<":"&lt;", ">":"&gt;", "\"":"&quot;", "'":"&#039;"}[char])); }
function styles() { return `
  .focusprofiles-settings{max-width:920px;color:var(--text-normal);display:grid;gap:16px;font-family:var(--font-primary)}
  .fp-header{display:flex;justify-content:space-between;gap:24px;align-items:start;padding:4px 2px}.fp-header h2{margin:0 0 6px;font-size:20px;letter-spacing:-.01em}.fp-header p,.fp-timer-note,.fp-empty{margin:0;color:var(--text-muted);font-size:12px;line-height:1.45}.fp-header p{max-width:650px}
  .fp-active{padding:11px 13px;border-radius:8px;border:1px solid color-mix(in srgb,var(--brand-500) 38%,transparent);background:linear-gradient(90deg,color-mix(in srgb,var(--brand-500) 17%,transparent),var(--background-secondary));font-size:13px}.fp-active strong{color:var(--header-primary)}
  .fp-list{display:grid;gap:10px}.fp-card{padding:15px;border-radius:10px;border:1px solid var(--background-modifier-accent);background:linear-gradient(135deg,var(--background-secondary),var(--background-secondary-alt,var(--background-secondary)));box-shadow:0 2px 8px rgba(0,0,0,.08);transition:border-color 150ms ease,box-shadow 150ms ease}.fp-card:hover{border-color:color-mix(in srgb,var(--brand-500) 42%,var(--background-modifier-accent))}.fp-card.is-active{border-color:var(--brand-500);box-shadow:0 0 0 1px color-mix(in srgb,var(--brand-500) 28%,transparent),0 8px 20px rgba(0,0,0,.12)}
  .fp-card-top{display:flex;gap:12px;justify-content:space-between}.fp-fields{display:flex;flex-wrap:wrap;gap:10px}.fp-fields label{display:grid;gap:5px;color:var(--text-muted);font-size:11px;font-weight:600;text-transform:uppercase;letter-spacing:.035em}.fp-fields input,.fp-fields select{min-width:128px;box-sizing:border-box;padding:8px 9px;border:1px solid var(--background-modifier-accent);border-radius:6px;background:var(--input-background);color:var(--text-normal);font:inherit;font-size:13px;font-weight:500;text-transform:none;letter-spacing:normal}.fp-fields input:focus,.fp-fields select:focus{outline:2px solid color-mix(in srgb,var(--brand-500) 55%,transparent);outline-offset:1px}
  .fp-card-actions{display:flex;gap:7px;align-items:end}.fp-button,.fp-icon,.fp-link,.fp-chip button{border:0;cursor:pointer;font:inherit}.fp-button{padding:8px 12px;border-radius:6px;background:var(--brand-500);color:#fff;font-weight:700;box-shadow:0 1px 3px rgba(0,0,0,.18);transition:filter 120ms ease,transform 120ms ease}.fp-button:hover{filter:brightness(1.08);transform:translateY(-1px)}.fp-secondary{background:var(--button-secondary-background);color:var(--button-secondary-text)}.fp-icon{width:32px;height:32px;border-radius:6px;background:var(--button-secondary-background);color:var(--text-normal);font-size:21px;line-height:1}.fp-icon:hover{background:var(--button-danger-background,#da373c);color:#fff}.fp-live{align-self:center;padding:4px 7px;border-radius:999px;background:color-mix(in srgb,var(--status-positive) 18%,transparent);color:var(--status-positive);font-size:11px;font-weight:700}.fp-dnd-text{display:grid;gap:5px;margin-top:12px;color:var(--text-muted);font-size:11px;font-weight:600;text-transform:uppercase;letter-spacing:.035em}.fp-dnd-text input{box-sizing:border-box;width:100%;padding:9px;border:1px solid var(--background-modifier-accent);border-radius:6px;background:var(--input-background);color:var(--text-normal);font:inherit;font-size:13px;font-weight:500;text-transform:none;letter-spacing:normal}.fp-timer-note{margin:11px 0 12px}
  .fp-schedule{display:flex;gap:8px;margin:0 0 12px}.fp-schedule-control{display:flex;align-items:center;gap:6px;padding:7px 9px;border:1px solid var(--background-modifier-accent);border-radius:7px;background:var(--background-tertiary);font-size:12px;font-weight:600}.fp-schedule-control span{color:var(--text-muted)}.fp-schedule-control select{border:0;background:transparent;color:var(--text-normal);font:inherit;font-size:12px;font-weight:600}.fp-time{display:flex;align-items:center;gap:2px;padding-left:5px;border-left:1px solid var(--background-modifier-accent)}.fp-time-input{width:48px;border:0;background:transparent;color:var(--text-normal);font:inherit;font-size:12px;font-weight:700}.fp-time-input:focus{outline:0;text-decoration:underline}.fp-time-period{width:36px}.fp-rules{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.fp-rule{padding:10px;border-radius:7px;background:var(--background-tertiary);border:1px solid transparent}.fp-rule:hover{border-color:var(--background-modifier-accent)}.fp-rule-top{display:flex;justify-content:space-between;gap:8px;align-items:center;font-size:12px}.fp-rule-note{margin:5px 0 0;color:var(--text-muted);font-size:11px;line-height:1.35}.fp-link{padding:2px 0;background:transparent;color:var(--text-link);font-size:12px;font-weight:600}.fp-link:hover{text-decoration:underline}.fp-chips{display:flex;flex-wrap:wrap;gap:5px;margin-top:9px;min-height:20px}.fp-chip{display:inline-flex;align-items:center;gap:5px;max-width:100%;padding:4px 5px 4px 8px;border-radius:999px;background:var(--background-modifier-hover);font-size:11px;font-weight:500}.fp-chip button{width:17px;height:17px;border-radius:50%;background:transparent;color:var(--text-muted);font-size:15px;line-height:13px}.fp-chip button:hover{background:var(--background-modifier-active);color:var(--text-normal)}.fp-add{justify-self:start;padding-inline:14px}@media(max-width:650px){.fp-header,.fp-card-top{display:grid}.fp-schedule,.fp-rules{display:grid;grid-template-columns:1fr}.fp-card-actions{justify-content:start}.fp-header .fp-button{justify-self:start}}
`; }
module.exports = {createSettingsPanel};
